### ISSUE TITLE
TT-GO Display fonts shifting right 

### ISSUE THREAD

**Issue by psyc0** [peterhinch/micropython-font-to-py#34]
Hi,

I realize that this might not be an issue in regards to this repo as the intended use with writer is not implemented, however I though I would give it a shot and any pointers would be appreciated.

So basically I'm trying to implement the DS-Digital Font on the https://github.com/russhughes/st7789_mpy driver for micropython and needed some large fonts for a scale. The font itself supports scaling 

```
fc-scan DS-DIGIB.TTF
Pattern has 22 elts (size 32)
        family: "DS-Digital"(s)
        familylang: "en"(s)
        style: "Bold"(s)
        stylelang: "en"(s)
        fullname: "DS-Digital Bold"(s)
        fullnamelang: "en"(s)
        slant: 0(i)(s)
        weight: 200(i)(s)
        width: 100(i)(s)
        foundry: "unknown"(s)
        file: "DS-DIGIB.TTF"(s)
        index: 0(i)(s)
        outline: True(s)
        scalable: True(s)
        charset: 
        0000: 00000000 ffffffff ffffffff 7fffffff 00000000 00000000 00000000 00000000
        0020: 32180000 00010004 00000000 00000000 00000000 00000000 00000000 00000000
(s)
        lang: fj|ho|ia|ie|io|nr|om|so|ss|st|sw|ts|uz|xh|zu|kj|kwm|ms|ng|rn|rw|sn|za(s)
        fontversion: 65536(i)(s)
        fontformat: "TrueType"(s)
        decorative: False(s)
        postscriptname: "DS-Digital-Bold"(s)
        color: False(s)
        symbol: False(s)
```

converted with:
`python3 font_to_py.py ds_digital/DS-DIGIB.TTF 96 -c 1234567890 -x -f digit.py`
trying out in terminal works just fine.
`python3 font_test.py digit 9`

the tft.text() function implemented takes the font as an input as long as I provide some extra vars:
WIDTH = 64    #(max_width)
HEIGHT = 96   #(height)
FIRST = 0x30  #(min_ch)
LAST = 0x3F  #(max_ch)
INDEX = memoryview(_index)
FONT = memoryview(_font)

parenthesis are given by functions in your output so thats what I reused for the display driver.
FIRST is also given by your script, but in that case it starts one char later since the ?/unknown seems to be first, so in my case with FIRST -1 the corresponding digits are shown for the correct input. 

however, my issue is that each char is slightly shifted right, i noticed this when looking at the code, basically where I marked in blue in the screenshot below is what is display on the lcd, and for each digit it is shifted, so 6 for example works just fine and is completely centered on screen, while 0 is just showing tho halves of the digit. Ie they start overlapping as if the width was wrong.

4,5,6 shown how they happen to align, and only 6 gets displayed correctly.
[https://imgur.com/a/qCwT6bP](https://imgur.com/a/qCwT6bP)

Im not sure if they are supposed to be compatible, the original devbis repo linked to your script as a resource so thats why I ended up here :)

I've tried to understand your code as well as I could but its a bit to low-level and intricate for me sadly. Any tips or ideas would help me alot. 
Thanks
